"""
Flask API server for the Multi-Digital Twin Wind Power Forecasting Dashboard.
Updated to load predictions from the Indian dataset (predictions/ directory).
"""

import os
import pandas as pd
from flask import Flask, jsonify, render_template, request
from mdt_engine import (
    get_single_dt_metrics,
    method1_single_metric,
    method2_multimetric_ds,
    compute_errors,
)

app = Flask(__name__)

# ── Load Indian dataset predictions at startup ────────────────────────────────
PRED_DIR   = os.path.join(os.path.dirname(__file__), "predictions")
MODEL_KEYS = ["LSTM", "GRU", "LSTMCNN", "GRUCNN"]


def load_indian_twin_data():
    """
    Load the 4 prediction CSVs generated by train_models.py.
    Each CSV has columns: idx, predicted, actual
    Returns a dict: {model_name: DataFrame}
    """
    twins = {}
    for name in MODEL_KEYS:
        path = os.path.join(PRED_DIR, f"{name}_preds.csv")
        if not os.path.exists(path):
            raise FileNotFoundError(
                f"Prediction file not found: {path}\n"
                "Run train_models.py first to generate predictions."
            )
        df = pd.read_csv(path)
        # Ensure correct column names expected by mdt_engine
        df.columns = ["idx", "predicted", "actual"]
        twins[name] = df
    print(f"[app] Loaded {len(twins)} twin prediction files from {PRED_DIR}/")
    for name, df in twins.items():
        print(f"  {name}: {len(df)} predictions  "
              f"pred_range=[{df['predicted'].min():.3f}, {df['predicted'].max():.3f}] (normalized)  "
              f"actual_range=[{df['actual'].min():.3f}, {df['actual'].max():.3f}] (normalized)")
    return twins


TWINS      = load_indian_twin_data()
TWIN_NAMES = list(TWINS.keys())
N_POINTS   = len(TWINS[TWIN_NAMES[0]])


# ── Routes ────────────────────────────────────────────────────────────────────

@app.route("/")
def index():
    return render_template("index.html", n_points=N_POINTS)


@app.route("/api/combinations")
def combinations():
    """Return all model combination results (Tables 5 & 6)."""
    csv_path = os.path.join(os.path.dirname(__file__), "combination_results.csv")
    df = pd.read_csv(csv_path)
    result = {}
    for group in df["group"].unique():
        g = df[df["group"] == group]
        result[group] = {}
        for method in g["method"].unique():
            rows = g[g["method"] == method][["combo","mae","rmse","mape","r2"]].to_dict("records")
            result[group][method] = rows
    return jsonify(result)


@app.route("/api/data")
def get_data():
    """Return raw time-series predictions for all 4 DTs and actual power."""
    result = {
        "actual": TWINS[TWIN_NAMES[0]]["actual"].tolist(),
        "twins": {}
    }
    for name in TWIN_NAMES:
        result["twins"][name] = TWINS[name]["predicted"].tolist()
    return jsonify(result)


@app.route("/api/metrics")
def get_metrics():
    """Return MAE / RMSE / R² for all 4 single DTs."""
    return jsonify(get_single_dt_metrics(TWINS))


@app.route("/api/mdt/method1")
def mdt_method1():
    """Method 1: Single Metric Dynamic Preference."""
    window = int(request.args.get("window", 20))
    window = max(2, min(window, 40))
    result = method1_single_metric(TWINS, window=window)
    return jsonify(result)


@app.route("/api/mdt/method2")
def mdt_method2():
    """Method 2: Multi-Metrics Dynamic Fusion (D-S Evidence Theory)."""
    window = int(request.args.get("window", 10))
    zeta   = float(request.args.get("zeta", 0.04))
    window = max(2, min(window, 40))
    zeta   = max(0.0, min(zeta, 0.2))
    result = method2_multimetric_ds(TWINS, window=window, zeta=zeta)
    return jsonify(result)


@app.route("/api/summary")
def summary():
    """Return a full summary: individual metrics + both MDT methods (default params)."""
    single  = get_single_dt_metrics(TWINS)
    m1      = method1_single_metric(TWINS, window=20)
    m2      = method2_multimetric_ds(TWINS, window=10, zeta=0.04)
    return jsonify({
        "n_points":   N_POINTS,
        "single_dts": single,
        "method1":    m1["metrics"],
        "method2":    m2["metrics"],
    })


if __name__ == "__main__":
    print("Starting MDT Wind Power Digital Twin Platform (Indian Dataset)...")
    print(f"Test set: {N_POINTS} hourly predictions")
    print("Open http://localhost:5001 in your browser")
    app.run(debug=False, port=5001)











